import type { Metadata } from "next";
import { Geist, Geist_Mono, Chiron_GoRound_TC } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chiron = Chiron_GoRound_TC({
  variable: "--font-chiron",
  subsets: ["latin"],
  fallback: ["sans-serif"],
})


export const metadata: Metadata = {
  title: "KDT03_Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kor">
      <body
        className={`${chiron.className} ${chiron.variable} antialiased`}
      >
        <div className="w-full h-screen flex flex-col bg-linear-to-br from-zinc-800 via-neutral-400/80 to-zinc-800 text-white">
          <Header />
          <main className=" overflow-y-auto scroll-smooth grow flex flex-col">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
